import React, { useState } from 'react';
import { Bike, Pencil, Trash2 } from 'lucide-react';
import { useApp } from '../../context/AppContext';

export const VehiclesView: React.FC = () => {
  const { customers, updateMotorcycle, deleteMotorcycle } = useApp();
  const [editing, setEditing] = useState<{ customerId: string; id: string; brand: string; model: string; plate: string; year: number } | null>(null);
  const vehicles = customers.flatMap((c) => c.motorcycles.map((m) => ({ c, m })));
  return <div className="space-y-6"><div><h1 className="text-2xl font-extrabold">Todos los vehículos</h1><p className="text-sm text-gray-600">Motocicletas registradas en Supabase.</p></div><div className="bg-white rounded-2xl border overflow-auto"><table className="w-full text-sm"><thead><tr className="text-left border-b"><th className="p-4">Vehículo</th><th className="p-4">Placa</th><th className="p-4">Cliente</th><th className="p-4">Acciones</th></tr></thead><tbody>{vehicles.map(({c,m}) => <tr key={m.id} className="border-b"><td className="p-4"><Bike className="inline w-4 mr-2" />{m.brand} {m.model} ({m.year || '—'})</td><td className="p-4">{m.licensePlate || '—'}</td><td className="p-4">{c.name}</td><td className="p-4 flex gap-2"><button onClick={() => setEditing({customerId:c.id,id:m.id,brand:m.brand,model:m.model,plate:m.licensePlate,year:m.year})}><Pencil className="w-4" /></button><button onClick={() => void deleteMotorcycle(c.id,m.id)}><Trash2 className="w-4 text-red-600" /></button></td></tr>)}</tbody></table>{!vehicles.length && <p className="p-8 text-center text-gray-500">No hay motocicletas registradas.</p>}</div>{editing && <div className="fixed inset-0 bg-black/40 flex items-center justify-center p-4"><form className="bg-white p-6 rounded-2xl space-y-3 w-full max-w-md" onSubmit={async e => {e.preventDefault(); await updateMotorcycle(editing.customerId,editing.id,{brand:editing.brand,model:editing.model,licensePlate:editing.plate,year:editing.year}); setEditing(null);}}><h2 className="font-bold">Editar motocicleta</h2>{(['brand','model','plate'] as const).map(k => <input key={k} className="w-full border rounded-xl p-2" value={editing[k]} onChange={e=>setEditing({...editing,[k]:e.target.value})} placeholder={k} />)}<input type="number" className="w-full border rounded-xl p-2" value={editing.year} onChange={e=>setEditing({...editing,year:Number(e.target.value)})} /><div className="flex justify-end gap-2"><button type="button" onClick={()=>setEditing(null)}>Cancelar</button><button className="bg-indigo-600 text-white px-4 py-2 rounded-xl">Guardar</button></div></form></div>}</div>;
};
